REM -- Outputs the molecular weight of a chemical formula

DIM ELEMENT_NAME$(63)
DIM ELEMENT_WEIGHT(63)

FOR I = 1 TO 63
  READ ELEMENT_NAME$(I), ELEMENT_WEIGHT(I)
NEXT I

PRINT "Write a chemical formula with no spaces like Li7N2Fe6"
INPUT CHEMICAL_COMPOSITION$

LET TOTAL_WEIGHT = 0
LET STR_INDEX = 1
LET CURRENT_ELEMENT$ = ""
WHILE STR_INDEX <> -1
  GOSUB GET_NEXT_ELEMENT_COUNT_PAIR
  LET CURRENT_ELEMENT = 0
  GOSUB GET_ELEMENT
  LET TOTAL_WEIGHT = TOTAL_WEIGHT + GET_E_WEIGHT()
WEND

PRINT "Total weight of the element is: "; TOTAL_WEIGHT

END

DEF GET_E_WEIGHT() = ELEMENT_WEIGHT(CURRENT_ELEMENT) * COUNT_ELEMENT

REM -- GET_NEXT_ELEMENT_COUNT_PAIR
REM -- Input is a global STR_INDEX and CHEMICAL_COMPOSITION$
REM -- Return is a global STR_INDEX, CURRENT_ELEMENT$ and NUM_CHEMICAL
GET_NEXT_ELEMENT_COUNT_PAIR:

  LET I = STR_INDEX
  LET TEMP$ = MID$(CHEMICAL_COMPOSITION$, I, 1)
  LET LETTER = 1
  WHILE (I < LEN(CHEMICAL_COMPOSITION$) + 1) AND LETTER
    IF ASC(MID$(CHEMICAL_COMPOSITION$,I,1)) < 48 OR ASC(MID$(CHEMICAL_COMPOSITION$,I,1)) > 57 THEN
      LET I = I + 1
    ELSE
      LET LETTER = 0
    END IF
  WEND
  LET SIZE_OF_ABBV = I - STR_INDEX

  LET I = SIZE_OF_ABBV + STR_INDEX
  LET NUMBER = 1
  WHILE (I < LEN(CHEMICAL_COMPOSITION$) + 1) AND NUMBER
    IF ASC(MID$(CHEMICAL_COMPOSITION$,I,1)) > 47 AND ASC(MID$(CHEMICAL_COMPOSITION$,I,1)) < 58 THEN
      LET I = I + 1
    ELSE
      LET NUMBER = 0
    END IF
  WEND
  LET SIZE_OF_NUMBER = I - (SIZE_OF_ABBV + STR_INDEX)

  LET CURRENT_ELEMENT$ = MID$(CHEMICAL_COMPOSITION$, STR_INDEX, SIZE_OF_ABBV)
  LET COUNT_ELEMENT = VAL( MID$( CHEMICAL_COMPOSITION$, STR_INDEX + SIZE_OF_ABBV, SIZE_OF_NUMBER ) )
  STR_INDEX = STR_INDEX + SIZE_OF_ABBV + SIZE_OF_NUMBER
  
  IF STR_INDEX > LEN(CHEMICAL_COMPOSITION$) THEN
    STR_INDEX = -1
  END IF

  RETURN


REM -- GET_ELEMENT subroutine
REM -- Input is a global CURRENT_ELEMENT$ string
REM -- Return is a global CURRENT_ELEMENT number
GET_ELEMENT:
  FOR I = 1 TO 63
    IF ELEMENT_NAME$(I) = CURRENT_ELEMENT$ THEN
      LET CURRENT_ELEMENT = I
      RETURN
    END IF
  NEXT I
  RETURN

DATA H, 1,    Li, 7,    Na, 23,    K, 39,    Cu, 63,    Rb, 85,    Ag, 108,    Cs, 133,    Au, 199
DATA Be, 9.4, Mg, 24,   Ca, 40,    Zn, 65,   Sr, 87,    Cd, 112,   Ba, 137,    Hg, 200
DATA B, 11,   Al, 27.3, Yt, 88,    In, 113,  Di, 138,   Er, 178,   Tl, 204
DATA C, 12,   Si, 28,   Ti, 48,    Zr, 90,   Sn, 118,   Ce, 140,   La, 180,    Pb, 207,    Th, 231
DATA N, 14,   P, 31,    V, 51,     As, 75,   Nb, 94,    Sb, 122,   Ta, 182,    Bi, 208
DATA O, 16,   S, 32,    Cr, 52,    Se, 78,   Mo, 96,    Te, 125,   W, 184,     U, 240
DATA F, 19,   Cl, 35.5, Mn, 55,    Br, 80,   I, 127
DATA Fe, 56,  Co, 59,   Ni, 59,    Ru, 104,  Rh, 104,   Pd, 106,   Os, 195,    Ir, 197,    Pt, 198
