PRINT "Input the texture, color, particles, and nicotine content in that order"
INPUT TEXTURE$, COLOR$, PARTICLES$, NICOTINE$

LET CIGAR$ = ""

IF TEXTURE$ = "FLAKY" OR TEXTURE$ = "CAKED" THEN
	LET STOCK = 1
ELSE
	LET STOCK = 2
END IF

IF NICOTINE$ = "++" AND PARTICLES$ = "NO" THEN
	LET NORMALITY$ = "NORMAL"
ELSE
	LET NORMALITY$ = "ABNORMAL"
END IF

IF NORMALITY$ = "NORMAL" AND STOCK = 1 THEN
	IF COLOR$ = "DARK" AND TEXTURE$ = "FLAKY" THEN
		LET CIGAR$ = "TRICHINOPOLY"
	ELSEIF COLOR$ = "DARK" AND TEXTURE$ = "CAKED" THEN
		LET CIGAR$ = "ESPANADA"
	ELSEIF COLOR$ = "DARK_GRAY" AND TEXTURE$ = "FLAKY" THEN
		LET CIGAR$ = "MACDUFFY"
	ELSEIF COLOR$ = "DARK_GRAY" AND TEXTURE$ = "CAKED" THEN
		LET CIGAR$ = "TOP HAT"
	ELSEIF COLOR$ = "LIGHT_GRAY" AND TEXTURE$ = "FLAKY" THEN
		LET CIGAR$ = "HERITAGE"
	ELSEIF COLOR$ = "BROWN_TINT" AND TEXTURE$ = "CAKED" THEN
		LET CIGAR$ = "LONDONER"
	END IF
END IF

IF NORMALITY$ = "NORMAL" AND STOCK = 2 THEN
	IF COLOR$ = "DARK_GRAY" AND TEXTURE$ = "GRANULAR" THEN
		LET CIGAR$ = "LUNKAH"
	ELSEIF COLOR$ = "LIGHT_GRAY" AND TEXTURE$ = "FLUFFY" THEN
		LET CIGAR$ = "WEST COUNTRY"
	END IF
END IF

IF NORMALITY$ = "ABNORMAL" THEN
	IF COLOR$ = "BROWN_TINT" AND NICOTINE$ = "+++" THEN
		LET CIGAR$ = "OLD WOOD"
	ELSEIF COLOR$ = "DARK" AND NICOTINE$ = "+" AND PARTICLES$ = "YES" THEN
		LET CIGAR$ = "LATINO"
	END IF
END IF

IF CIGAR$ = "" THEN
	PRINT "*** Unidentified "; NORMALITY$; " CIGAR OF STOCK "; STOCK
ELSE
	PRINT "Cigar is a(n) "; CIGAR$
END IF
