REM -- Constants
LET MINS_PER_HOUR = 60
LET HOURS_PER_DAY = 24
LET MINS_PER_DAY = HOURS_PER_DAY * MINS_PER_HOUR
LET MINS_PER_TIDE_CYCLE = 745

INPUT TODAYS_DATE, TIDE_HR, EVENT_DATE, EVENT_HR

LET MINS_TO_HIGH_TIDE = ((TODAYS_DATE - 1) * MINS_PER_DAY) + (TIDE_HR * MINS_PER_HOUR)

LET MINS_TO_EVENT = ((EVENT_DATE - 1) * MINS_PER_DAY) + (EVENT_HR * MINS_PER_HOUR)

LET TIME_BETWEEN_EVENT_AND_TODAY = MINS_TO_HIGH_TIDE - MINS_TO_EVENT

LET TIDE_CYCLES = TIME_BETWEEN_EVENT_AND_TODAY / MINS_PER_TIDE_CYCLE

PRINT "Number of tide cycles that transpired between the event and current high tide:"
PRINT TIDE_CYCLES

PRINT "During the disappearance it was:"
LET TIDE_CYCLES_REMAINDER = TIDE_CYCLES - INT(TIDE_CYCLES)
IF TIDE_CYCLES_REMAINDER > 0.25 AND TIDE_CYCLES_REMAINDER < 0.75 THEN
	PRINT "Low Tide"
ELSE
	PRINT "High Tide"
END IF
