PRINT "DEPARTING      OXFORD          TOTAL"
PRINT "  TRAIN      CONNECTION       JOURNEY"
PRINT "---------    ----------       -------"

REM - I'll be real here, it's doubtful the authors were expecting us to do a full run
REM - of this code. The train timetable is incomplete, but using the sample, this program
REM - at least seems to match the first row in Homes's output table.

INPUT CITY$, START_TIME

WHILE CITY$ <> "OXFORD"
	INPUT CITY$, STOP_TIME
WEND

WHILE CITY$ <> "LONDON"
	INPUT CITY$, ARRIVAL_TIME
WEND

FOR TRAIN_NUM = 2 TO 10
	INPUT CITY$, NEXT_START_TIME
	WHILE CITY$ <> "OXFORD"
		INPUT CITY$, NEXT_STOP_TIME
	WEND
	WHILE CITY$ <> "LONDON"
		INPUT CITY$, NEXT_ARRIVAL_TIME
	WEND

	LET CONNECTION = NEXT_STOP_TIME - STOP_TIME
	LET STOP_TIME_HRS = INT( STOP_TIME / 100 )
	LET NEXT_STOP_TIME_HRS = INT( NEXT_STOP_TIME / 100 )
	LET STOP_TIME_MINS = STOP_TIME - ( STOP_TIME_HRS * 100 )
	LET NEXT_STOP_TIME_MINS = NEXT_STOP_TIME - ( NEXT_STOP_TIME_HRS * 100 )
	
	IF STOP_TIME_MINS > NEXT_STOP_TIME_MINS THEN
		LET CONNECTION = CONNECTION - 40
	END IF

	LET JOURNEY = NEXT_ARRIVAL_TIME - START_TIME
	LET START_TIME_HRS = INT( START_TIME / 100 )
	LET NEXT_ARRIVAL_TIME_HRS = INT( NEXT_ARRIVAL_TIME / 100 )
	LET START_TIME_MINS = START_TIME - ( START_TIME_HRS * 100 )
	LET NEXT_ARRIVAL_TIME_MINS = NEXT_ARRIVAL_TIME - ( NEXT_ARRIVAL_TIME_HRS * 100 )

	IF START_TIME_MINS > NEXT_ARRIVAL_TIME_MINS THEN
		LET JOURNEY = JOURNEY - 40
	END IF

	PRINT TRAIN_NUM - 1, CONNECTION, JOURNEY

	LET START_TIME = NEXT_START_TIME
	LET STOP_TIME = NEXT_STOP_TIME
NEXT TRAIN_NUM

PRINT "Times of all trains from BIRMINGHAM to LONDON with a stop in OXFORD"
