REM -- Takes in an initial offset, keyword, and ciphertext to decode messages ciphered by the Alphabet Cipher

PRINT "Requires OFFSET, KEYWORD$, CIPHERTEXT$"
INPUT OFFSET, KEYWORD$, CIPHERTEXT$

LET ALPHABET$ = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
LET ALPHABET_LENGTH = LEN(ALPHABET$)
LET A_INDEX = ASC("A")

LET KEYWORD_LENGTH = LEN(KEYWORD$)
LET CURRENT_INDEX = 1
LET KEYWORD_INDEX = 1
LET RESULT_STR$ = ""

WHILE CURRENT_INDEX <= LEN(CIPHERTEXT$)
	LET CIPHERTEXT_CHAR$ = MID$(CIPHERTEXT$, CURRENT_INDEX, 1)

	IF CIPHERTEXT_CHAR$ <> " " THEN
		IF KEYWORD_INDEX > KEYWORD_LENGTH THEN
			KEYWORD_INDEX = 1
		END IF
		LET KEYWORD_CHAR$ = MID$(KEYWORD$, KEYWORD_INDEX, 1)
		REM -- KEYWORD_VALUE is 0 indexed, since it determines how many columns to the right we should go
		LET KEYWORD_VALUE = ASC(KEYWORD_CHAR$) - A_INDEX
	
		REM -- CIPHERTEXT_VALUE is 0 indexed, since it determines how many rows down we should go
		LET CIPHERTEXT_VALUE = ASC(CIPHERTEXT_CHAR$) - A_INDEX

		LET ALPHABET_INDEX = OFFSET + CIPHERTEXT_VALUE + KEYWORD_VALUE
		IF ALPHABET_INDEX > ALPHABET_LENGTH THEN
			ALPHABET_INDEX = ALPHABET_INDEX - ALPHABET_LENGTH
		END IF

		LET RESULT_STR$ = RESULT_STR$ + MID$(ALPHABET$, ALPHABET_INDEX, 1)
		LET KEYWORD_INDEX = KEYWORD_INDEX + 1
	ELSE
		LET RESULT_STR$ = RESULT_STR$ + " "
	END IF

	LET CURRENT_INDEX = CURRENT_INDEX + 1
WEND

PRINT "Ciphered message: "; RESULT_STR$

